[profile.default]
# Compilation
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100000

# Testing
gas_reports = ["*"]
verbosity = 3
chain_id = 99
block_timestamp = 2592000

[profile.ci.fuzz]
runs = 500

[profile.default.fuzz]
runs = 100

[profile.default.invariant]
runs           = 100    # The number of calls to make in the invariant tests
depth          = 100    # The number of times to run the invariant tests
call_override  = false  # Override calls
fail_on_revert = true   # Fail the test if the contract reverts

[profile.default.fmt]
int_types = "preserve"
number_underscore = "preserve"

[profile.default.rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
tenderly = "${TENDERLY_FORK_URL}"

# forge script --chain mainnet script/DeployLocal.s.sol:DeployLocalScript --rpc-url https://eth-mainnet.alchemyapi.io/v2/B4w2ueJLjihQPuf868vthxg7FvfND5i5
# forge script --chain sepolia script/DeploySepolia.s.sol:DeploySepoliaScript --rpc-url https://eth-sepolia.g.alchemy.com/v2/6U2Z1L4BEW2VkZeHS5NQAWrvciif1DDI
